### ISSUE TITLE
suggestion: task 8 2d mesh tally plotting 

### ISSUE THREAD

**Issue by py1sl** [fusion-energy/neutronics-workshop#17]
In the 2d mesh plotting example, the source is at  0 0 0 in co-ordinate space, but in the 2d plots it is located at 50, 50 as it is the mesh index.  If the source is moved up  in +Z direction it will move down in the plot, which may confuse some students as they start to use their own models etc. 
Possibly would be useful to expand the example to demonstrate how to make the axis of the plot match the geometry co-ordinates.

**Comment by Shimwell** [comment]
Sorry for the slow reply here.

I've added and explanation and centred the plot.

So this is fixed after the PR gets into the develop then main

In the mean time here is the code in case it is handy


```python
# when plotting the 2d data, added the extent is required.
# otherwise the plot uses the index of the 2d data arrays
# as the x y axis
plt.show(fig.imshow(my_slice.mean, extent=[-200,200,-200,200]))
```

Thanks for reporting
