### ISSUE TITLE
Filepath in Task 1 Part 4

### ISSUE THREAD

**Issue by eleanorwinkler** [fusion-energy/neutronics-workshop#209]
Hello! I ran into an issue in part 4 of tast 1, where I was getting errors saying that there was no such file or directory for the h5 file, but when I changed it to 'h5_file = f"/WMP_Library/074186.h5"', it worked. 
<img width="1095" alt="Screen Shot 2023-05-30 at 4 33 15 PM" src="https://github.com/fusion-energy/neutronics-workshop/assets/135072620/cf0257b2-496d-4648-bdb9-ffb17b4e4cd4">

**Comment by shimwell** [comment]
Awesome find thanks for reporting this.

Wondering if you keen to make a pull request to fix this? No worries if not I shall get this fixed tomorrow

**Comment by shimwell** [comment]
thanks for raising this issue, I've now pushed to fix to the main branch.
