### ISSUE TITLE
Missing geometry definition issues - task_06_simple_csg_geometry

### ISSUE THREAD

**Issue by JoelLucaAdams** [fusion-energy/neutronics-workshop#267]
# Issue description
It looks like the task listed above is missing material definitions in cells 2, 3 and 4

## Code example
It should look like this:
```python
blanket_cell = openmc.Cell(region=blanket_region)
blanket_cell.fill = lithium_mat  # this assigns a material to a cell
```

Currently looks like:
```python
blanket_cell = openmc.Cell(region=blanket_region)
```

**Comment by shimwell** [comment]
Thansk for raising the issue

I think this is actually ok, cells 2, 3, and 4 plot the geometry by cells

it is not till the 5 code block where the materials are added and we plot by material

**Comment by JoelLucaAdams** [comment]
Yeah that makes a lot of sense, I'll close the issue then
