### ISSUE TITLE
Problem with the ring source plotting

### ISSUE THREAD

**Issue by louishennion** [fusion-energy/neutronics-workshop#84]
Hello, 
I am completing the workshop and I've run into a problem with the 2nd part of the 4th task.
When I try to plot the source defined in this part, I have the following error : 
"ERROR: Invalid spatial distribution for external source: cylindrical"
I have not changed the default settings.
Do you know where it might come from ?
Thank you

<img width="1131" alt="Screenshot 2022-04-06 at 09 59 23" src="https://user-images.githubusercontent.com/93596185/161992090-af52319b-ef18-443f-80c0-a9c83e9aa01e.png">

**Comment by shimwell** [comment]
Ah yes sorry about this.

We are a bit stuck with this particular source plotting at the moment for a few reasons

currently we use https://github.com/fusion-energy/openmc_source_plotter to plot sources. However ...

the latest version of openmc  (0.13.0) does not write an initial source file for fixed sources but has the ring source functionality
the older version (0.11.0) writes the initial source file but dose not have the ring source functionality.

However we have a plan which is about 2 months away to fix all of this.

We will add initial source sampling to the openmc.lib methods and then we will be able to sample sources without writing an initial source file for all sources :tada:

Once that feature is in openmc we will have a bump version release of openmc and then I shall rewrite [this](https://github.com/fusion-energy/openmc_source_plotter) package to make use of the openmc.lib method of getting source properties

I can post back here once this has been completed but you can also keep track by watching the various repos as this work is all being done in the public domain. For example here is a related issue https://github.com/openmc-dev/openmc/issues/1537

**Comment by shimwell** [comment]
This issue is not totally solved but there has been some progress as the sampling of source energy is now performed using the openmc.source.energy.sample method.

There are still a few things (allow location and direction sampling via python api in openmc) to do but happy to report some progress

**Comment by shimwell** [comment]
I believe this issue is now solved

the latest develop branch of openmc supports source sampling with openmc.lib

[oenmc_source_plotter](https://github.com/fusion-energy/openmc_source_plotter/) has been updated to version 0.4.1 and the workshop is making use of that version
